// `kelp explain` — the long-form manual. Prints to stdout so `kelp explain
// | less` works. Covers what the tool actually does, when to use each
// depth, how much a run costs, and the important safety guarantees
// (evidence-gating, no-network-egress for static, redacted transcripts).
//
// Users who only read --help won't discover half the surface area, so this
// exists as the "one page you actually read once" companion.

import { c } from "../ui/style.js";

function h(title: string): string {
  return "\n" + c.bold(c.cyan("━━ " + title + " ")) + c.dim("━".repeat(Math.max(2, 78 - title.length - 4))) + "\n\n";
}

function kv(label: string, val: string): string {
  return `  ${c.dim(label.padEnd(16))} ${val}\n`;
}

export function explain(): void {
  const out = process.stdout;
  out.write(`\n${c.bold("kelp")} — security scanner for vibe-coded apps.\n`);
  out.write(c.dim("The manual. Read once, then never think about it again.\n"));

  out.write(h("WHAT KELP DOES"));
  out.write(
    `  Kelp scans Supabase/Next.js apps generated by AI coding tools for the\n` +
    `  small set of mistakes those tools reliably make. Two engines:\n\n` +
    `  ${c.bold("static")}   Local, offline, free. Regex + entropy for secrets,\n` +
    `           TOML parse for edge-fn misconfig, walker for edge-fn recon.\n` +
    `           No network, no LLM. Run this in CI.\n\n` +
    `  ${c.bold("agent")}    Opt-in via ${c.bold("--agent")}. Sends file bytes to Anthropic and\n` +
    `           runs a bounded loop: read/grep/list_files, then file findings.\n` +
    `           Every finding is evidence-gated (see SAFETY below).\n`
  );

  out.write(h("DEPTH — how deep the agent goes"));
  out.write(
    `  Pick one preset. Each combines model + cost cap + iteration cap.\n\n` +
    kv("quick",    c.bold("claude-haiku-4-5") + c.dim("  · $0.15  · 10 iter  · smoke test")) +
    kv("standard", c.bold("claude-sonnet-5") + c.dim("   · $1.00  · 24 iter  · default")) +
    kv("thorough", c.bold("claude-sonnet-5") + c.dim("   · $3.00  · 40 iter  · pre-launch audit")) +
    kv("paranoid", c.bold("claude-opus-5") + c.dim("     · $10.00 · 80 iter  · full pentest")) +
    `\n  You can override any single knob: ${c.bold("--model")} · ${c.bold("--max-cost-cents")} · ${c.bold("--max-iterations")}.\n`
  );

  out.write(h("FOCUS — narrow what the agent looks for"));
  out.write(
    `  ${c.bold("--focus")} takes a comma-separated list. When set, the agent only\n` +
    `  files findings from these classes (still reads freely to build context):\n\n` +
    kv("secrets",   "hardcoded API keys, service-role tokens, private keys") +
    kv("auth",      "missing auth checks, ${AUTH_USER_ID} confusion, cookie mistakes") +
    kv("rls",       "createClient() with service_role on client, RLS-bypassing routes") +
    kv("edge-fn",   "verify_jwt=false, missing authz in Supabase functions") +
    kv("redirects", "open redirects, unvalidated next-url params") +
    `\n  Without --focus the agent considers everything it knows about.\n`
  );

  out.write(h("OBSERVATIONS — soft hints without evidence"));
  out.write(
    `  ${c.bold("--observations")} surfaces the agent's "I noticed X but can't cite a\n` +
    `  line" hunches as a separate section. Never mixed with findings. Turn on\n` +
    `  when you're doing an audit and want the full mental map.\n`
  );

  out.write(h("REPORT — write findings to a file"));
  out.write(
    `  ${c.bold("--report out.html")}    styled HTML, opens with double-click\n` +
    `  ${c.bold("--report out.md")}      Markdown, good for PR descriptions\n` +
    `  ${c.bold("--json")}                machine-readable, unchanged\n\n` +
    `  The report includes: findings, observations (if any), agent run summary,\n` +
    `  and remediation hints per rule.\n`
  );

  out.write(h("SAFETY — what Kelp will and won't do"));
  out.write(
    `  ${c.bold("Evidence-gated.")}      The agent never decides a finding is real. It\n` +
    `                        must supply a substring at path:line; the CLI\n` +
    `                        re-verifies. Fabricated findings are dropped.\n\n` +
    `  ${c.bold("Redacted transcript.")} Tool results (file bytes, grep matches) never\n` +
    `                        enter the streaming log. You see "read_file →\n` +
    `                        2.1 KB", not the actual bytes.\n\n` +
    `  ${c.bold("Local only, static.")}  The static engine never leaves your machine.\n` +
    `                        No telemetry, no phone-home.\n\n` +
    `  ${c.bold("Cost-capped.")}         The agent stops at --max-cost-cents. You\n` +
    `                        cannot accidentally run up a $100 bill.\n`
  );

  out.write(h("EXAMPLES"));
  out.write(
    `  ${c.bold("kelp scan .")}\n` +
    `    Static scan of the current directory.\n\n` +
    `  ${c.bold("kelp scan . --agent --depth thorough")}\n` +
    `    Static + agent audit with sonnet, $3 cap.\n\n` +
    `  ${c.bold("kelp scan . --agent --depth paranoid --focus auth,rls --report audit.html")}\n` +
    `    Opus deep-dive on auth + RLS only, writes styled HTML report.\n\n` +
    `  ${c.bold("kelp scan . --agent --dry-run")}\n` +
    `    Show plan + estimated cost without calling the API.\n\n` +
    `  ${c.bold("kelp scan . --json > findings.json")}\n` +
    `    CI-friendly output. Non-zero exit code on findings.\n`
  );

  out.write(h("COMMANDS"));
  out.write(
    kv("scan", "run a scan — see `kelp scan --help`") +
    kv("explain", "this page") +
    kv("list-rules", "every check the CLI runs, with rule ids") +
    kv("config", "show effective config (env + ~/.config/kelp/config.json)") +
    kv("--version", "print version")
  );

  out.write(h("CONFIG"));
  out.write(
    `  Anthropic key: env ${c.bold("ANTHROPIC_API_KEY")} wins over the file.\n` +
    `  File location: ${c.bold("~/.config/kelp/config.json")}\n\n` +
    `      { "anthropicApiKey": "sk-ant-..." }\n\n` +
    `  Run ${c.bold("kelp config")} to see what's active.\n`
  );

  out.write(h("LINKS"));
  out.write(
    kv("docs",   "https://kelp.build/docs") +
    kv("action", "https://github.com/Mic52M/kelp-action") +
    kv("source", "https://github.com/Mic52M/kelp") +
    kv("issues", "https://github.com/Mic52M/kelp/issues")
  );
  out.write("\n");
}
