// Opens (or reuses) the "Enable kelp/check on this repository" PR — the
// one-click on-ramp to #36. Callable from the connect flow (silent) and
// from the dashboard button. Idempotent per project: repeated calls reuse
// the existing open PR or short-circuit when the workflow file is already
// on the default branch.
//
// Requires `Workflows: write` permission on the Kelp GitHub App —
// GitHub rejects writes to .github/workflows/* otherwise (403). We surface
// that failure as `needs_permission` so the UI can prompt the user to
// re-authorize.

import { getPool, loadProject } from "./db.js";
import { createGitHubConnector } from "./connectors/github.js";

const WORKFLOW_PATH = ".github/workflows/kelp-check.yml";
const BRANCH = "kelp/enable-check";

function requireEnv(name: string): string {
  const v = process.env[name];
  if (!v) throw new Error(`missing env ${name}`);
  return v;
}

function kelpBaseUrl(): string {
  return (process.env.KELP_APP_BASE_URL ?? "https://kelp.dev").replace(/\/+$/, "");
}

/** Which Action repo to reference in the generated workflow. Overridable
 *  during dev, defaults to the current published slug. Kept in one place so
 *  the transfer to `kelp-security/kelp-action` is a one-line change. */
function actionSlug(): string {
  return process.env.KELP_ACTION_REPO ?? "Mic52M/kelp-action";
}

function actionRef(): string {
  return process.env.KELP_ACTION_REF ?? "v1";
}

/** The workflow file we commit. Uses the current Kelp API base as
 *  kelp-url when it's non-default (dev/staging), otherwise omits the
 *  input so the Action's default (https://kelp.dev) applies. */
function renderWorkflow(): string {
  const base = kelpBaseUrl();
  const kelpUrlLine =
    base === "https://kelp.dev" ? "" : `\n        with:\n          kelp-url: ${base}\n`;
  return `# Auto-generated by Kelp. Safe to edit; Kelp only re-adds this file if it goes missing.
name: kelp/check
on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: ${actionSlug()}@${actionRef()}${kelpUrlLine}`;
}

const PR_TITLE = "Enable kelp/check on this repository";

function renderPrBody(): string {
  const base = kelpBaseUrl();
  return [
    "Kelp opened this PR to add the `kelp/check` GitHub Action to your repository.",
    "",
    "**What it does**: on every pull request, Kelp scans the diff for new security findings — hardcoded secrets, permissive CORS, insecure edge functions, RLS misconfigurations — and fails the check when the PR introduces new critical or high severity issues.",
    "",
    "**Setup after merge**:",
    "1. Merge this PR — the workflow starts running on the next pull request automatically.",
    "2. To make Kelp _block_ merges, add `kelp/check` as a required status check in **Settings → Branches → Branch protection rules**.",
    "",
    `**Learn more**: [${base}/docs/action](${base}/docs/action)`,
    "",
    "---",
    "*This PR was opened automatically when you connected the repo. If you'd rather add the workflow manually, close this PR and copy the snippet from the docs.*",
  ].join("\n");
}

export type EnableCheckPrResult =
  | { ok: true; status: "opened" | "already_open" | "already_enabled"; url: string | null }
  | { ok: false; error: "no_repo" | "no_installation" | "needs_permission" | "internal"; message: string };

/** Open (or reuse) the enable-kelp/check PR for a project. Never throws —
 *  callers (silent connect-time invocation, dashboard button) get a typed
 *  result they can render. */
export async function openEnableCheckPr(
  projectId: string,
): Promise<EnableCheckPrResult> {
  const project = await loadProject(projectId);
  if (!project) {
    return { ok: false, error: "no_repo", message: "Project not found." };
  }
  if (!project.repoFullName) {
    return { ok: false, error: "no_repo", message: "This project isn't linked to a GitHub repo." };
  }
  if (project.installationId == null) {
    return { ok: false, error: "no_installation", message: "The Kelp GitHub App isn't installed on this repo's org." };
  }

  const gh = createGitHubConnector({
    appId: requireEnv("GITHUB_APP_ID"),
    privateKey: Buffer.from(requireEnv("GITHUB_APP_PRIVATE_KEY_BASE64"), "base64").toString("utf8"),
    installationId: project.installationId,
  });

  try {
    const res = await gh.openFileCreationPr(project.repoFullName, {
      branch: BRANCH,
      title: PR_TITLE,
      body: renderPrBody(),
      commitMessage: "Add kelp/check workflow",
      path: WORKFLOW_PATH,
      content: renderWorkflow(),
    });

    if (res.status === "file_already_exists") {
      await getPool().query(
        `update projects set enable_check_pr_url = null, enable_check_pr_opened_at = null where id = $1`,
        [projectId],
      );
      return { ok: true, status: "already_enabled", url: null };
    }
    if (res.status === "already_open") {
      await getPool().query(
        `update projects set enable_check_pr_url = $2 where id = $1 and enable_check_pr_url is distinct from $2`,
        [projectId, res.url],
      );
      return { ok: true, status: "already_open", url: res.url };
    }
    // opened fresh
    await getPool().query(
      `update projects set enable_check_pr_url = $2, enable_check_pr_opened_at = now() where id = $1`,
      [projectId, res.url],
    );
    return { ok: true, status: "opened", url: res.url };
  } catch (e) {
    const status = (e as { status?: number }).status;
    const msg = e instanceof Error ? e.message : String(e);
    if (status === 403 && /workflow/i.test(msg)) {
      return {
        ok: false,
        error: "needs_permission",
        message:
          "Kelp needs the Workflows: write permission on your GitHub App install to add this file. Accept the new permissions from GitHub, then click Enable again.",
      };
    }
    console.warn("openEnableCheckPr failed:", msg);
    return { ok: false, error: "internal", message: "GitHub rejected the request — try again in a minute." };
  }
}

/** Fast check: does the workflow file already exist on the default branch?
 *  Used by the dashboard to promote the panel to the "enabled" state
 *  without round-tripping to open a PR that would short-circuit anyway. */
export async function isCheckEnabled(projectId: string): Promise<boolean> {
  const project = await loadProject(projectId);
  if (!project?.repoFullName || project.installationId == null) return false;
  const gh = createGitHubConnector({
    appId: requireEnv("GITHUB_APP_ID"),
    privateKey: Buffer.from(requireEnv("GITHUB_APP_PRIVATE_KEY_BASE64"), "base64").toString("utf8"),
    installationId: project.installationId,
  });
  try {
    const exists = await gh.fileExistsOnDefaultBranch(project.repoFullName, WORKFLOW_PATH);
    if (exists) {
      // Sync DB when we notice the workflow landed since we last opened a PR.
      await getPool().query(
        `update projects
         set enable_check_pr_url = null, enable_check_pr_opened_at = null
         where id = $1 and enable_check_pr_url is not null`,
        [projectId],
      );
    }
    return exists;
  } catch (e) {
    console.warn("isCheckEnabled failed:", e instanceof Error ? e.message : e);
    return false;
  }
}

/** Snapshot of the PR-check enable state, for the dashboard. */
export interface EnableCheckStatus {
  enabled: boolean;
  prUrl: string | null;
  prOpenedAt: string | null;
}

export async function loadEnableCheckStatus(projectId: string): Promise<EnableCheckStatus> {
  const enabled = await isCheckEnabled(projectId);
  const { rows } = await getPool().query(
    `select enable_check_pr_url, enable_check_pr_opened_at from projects where id = $1`,
    [projectId],
  );
  const row = rows[0] ?? {};
  return {
    enabled,
    prUrl: enabled ? null : (row.enable_check_pr_url ?? null),
    prOpenedAt: enabled
      ? null
      : row.enable_check_pr_opened_at
        ? new Date(row.enable_check_pr_opened_at).toISOString()
        : null,
  };
}
